"""Add location column to contracts

Revision ID: 442a6f9fd1a0
Revises: 
Create Date: 2025-09-12 12:47:01.469497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442a6f9fd1a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###   
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('service', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('product', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hsn_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ordered_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.drop_column('prices')
        batch_op.drop_column('quantities')
        batch_op.drop_column('services_products')
        batch_op.drop_column('status')
        batch_op.drop_column('categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('services_products', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('quantities', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('prices', sa.TEXT(), nullable=True))
        batch_op.drop_column('price')
        batch_op.drop_column('ordered_quantity')
        batch_op.drop_column('hsn_code')
        batch_op.drop_column('model')
        batch_op.drop_column('brand')
        batch_op.drop_column('product')
        batch_op.drop_column('category_name')
        batch_op.drop_column('service')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
